### ISSUE TITLE
fix hidden YAML decoding issues by returning a proper exit code

### ISSUE THREAD

**Issue by jolbax** [camptocamp/helm-sops#21]
Pull request #20 solves the problem of ArgoCD applications not being correctly rendered. The scenario look as follow:

If any YAML file going through the "DetectSopsYaml" has incorrectly a duplicated key (see below) like this:

```
data:
  value1: foo
  value2: bar
  value1: foobar
```
then the decoding of this file will cause following error log with the system exit code 0

`unmarshal errors: line 4: mapping key "value1" already defined at line 2`

the file is being then skipped causing that the Chart is not being correctly rendered and ArgoCD does not get any information about the YAML error but instead it gets a bad rendered Chart.

**Comment by jolbax** [comment]
Hi @hbollon, @yann-soubeyrand, 
Maybe any of you have time to have a look on this issue and the proposed solution?
It would be great

**Comment by hbollon** [comment]
Merged #20
