### ISSUE TITLE
Optionally toggle `secretFilenameRegexp`

### ISSUE THREAD

**Issue by igaskin** [camptocamp/helm-sops#3]
_Use case_

Restricting the decryption of files to those with the word "secrets" in the filename enforces a regex that can also be included as part of the `.sops.yaml` configuration file as a `path_regex`.  This can produce a strange user-experience, in which the `.sops.yaml` is inclusive a given set of files, but the regex in `helm-sops` excludes it.

https://github.com/mozilla/sops#210using-sopsyaml-conf-to-select-kmspgp-for-new-files

**Comment by yann-soubeyrand** [comment]
Hi @igaskin,

This behavior is inherited from Helm secrets plugin (the Helm plugin which inspired Helm Sops). Indeed, getting secret filename regexp from .sops.yaml file could be nice. However, I won't have the time to work on it soon. But we're open to pull requests ;-)

**Comment by hbollon** [comment]
Fixed in #9 which is released :tada:
