### ISSUE TITLE
Limitation on secrets filenames is a poor UX

### ISSUE THREAD

**Issue by tyrken** [camptocamp/helm-sops#8]
The `secrets*.yaml` type naming restriction is a bit awkward - it's a bad user experience that has tripped me up a few times even when I knew it existed. It misses out on matching `.yml` files or `secret-things.yaml`, and at least some more recent forks of the plugin (e.g. https://github.com/jkroepke/helm-secrets that I use) have no such restriction - so `helm secrets xxx` works and helm-sops doesn't.

Can you not peek at every values-file in the argument list, and see if they contain a valid-looking sops/version key so its likely it's a sops file?

This was also requested on the original futuresimple version, see https://github.com/zendesk/helm-secrets/pull/155.

**Comment by yann-soubeyrand** [comment]
Could be great, indeed! PR welcome ;-)

**Comment by hbollon** [comment]
Fixed in #9 which is now released :tada:
